### PR TITLE
replace : by _ in path

### PR DESCRIPTION
**Pull request by fritteli**

### CODE REVIEW

**Comment by fritteli** [comment]
This PR should fix #75

**Comment by fnfilho** [comment]
+1

**Comment by fernandofleury** [comment]
Can you guys check the 1.1.0 release? It seems like @QuentinFchx already provided a fix for it.

**Comment by fernandofleury** [comment]
@fritteli @fnfilho

**Comment by fernandofleury** [comment]
Closing this PR. If you guys have any issues we can discuss it again.

**Pull request closed without merging**
