### PR TITLE
Organization code

### PR DESCRIPTION
**Pull request by matheusca**
This PR tried remove some logic `VMasker` into split files.

PS: This an initial extract and I appriciate your feedback.

### CODE REVIEW

**Comment by regishideki** [comment]
It's nice!!! Congrats =)

**Comment by leandroadacosta** [comment]
The name of files can be using underscore instead hifen.

**Comment by matheusca** [comment]
I search for one good solution about named files.

I saw in jquery repository is used with hifen solution. I check it out: https://github.com/jquery/jquery/tree/master/src

Maybe we could use like jquery does.

What do you think?

**Comment by mcapanema** [comment]
Seems fair to me :+1:

**Comment by fernandofleury** [comment]
I think we can close this PR for now. Refactoring the actual codebase nowadays could definitely absorb a few concepts from this, but I guess starting from scratch is a better approach.

**Pull request closed without merging**
